// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission4TreyJackson.Models;

namespace Mission4TreyJackson.Migrations
{
    [DbContext(typeof(movieEntryContext))]
    [Migration("20230214073241_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission4TreyJackson.Models.movieEntry", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Crime/Drama",
                            Director = "Francis Ford Coppola",
                            Edited = "False",
                            LentTo = "",
                            Notes = "Greatest of all time!",
                            Rating = "R",
                            Title = "The Godfather",
                            Year = 1972
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "War/Drama",
                            Director = "Sam Mendes",
                            Edited = "True",
                            LentTo = "",
                            Notes = "Favorite War Movie",
                            Rating = "R",
                            Title = "1917",
                            Year = 2019
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Romance",
                            Director = "Michel Gondry",
                            Edited = "False",
                            LentTo = "",
                            Notes = "Favorite Romance",
                            Rating = "R",
                            Title = "Eternal Sunshine of the Spotless Mind",
                            Year = 2004
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
