// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission4TreyJackson.Models;

namespace Mission4TreyJackson.Migrations
{
    [DbContext(typeof(movieEntryContext))]
    partial class movieEntryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission4TreyJackson.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Drama"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "Romance"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Horror"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Comedy"
                        },
                        new
                        {
                            CategoryID = 5,
                            CategoryName = "Documentary"
                        });
                });

            modelBuilder.Entity("Mission4TreyJackson.Models.movieEntry", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Edited")
                        .HasColumnType("TEXT");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.HasIndex("CategoryID");

                    b.ToTable("movieEntry");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            CategoryID = 1,
                            Director = "Francis Ford Coppola",
                            Edited = "False",
                            LentTo = "",
                            Notes = "Greatest of all time!",
                            Rating = "R",
                            Title = "The Godfather",
                            Year = 1972
                        },
                        new
                        {
                            MovieID = 2,
                            CategoryID = 1,
                            Director = "Sam Mendes",
                            Edited = "True",
                            LentTo = "",
                            Notes = "Favorite War Movie",
                            Rating = "R",
                            Title = "1917",
                            Year = 2019
                        },
                        new
                        {
                            MovieID = 3,
                            CategoryID = 2,
                            Director = "Michel Gondry",
                            Edited = "False",
                            LentTo = "",
                            Notes = "Favorite Romance",
                            Rating = "R",
                            Title = "Eternal Sunshine of the Spotless Mind",
                            Year = 2004
                        });
                });

            modelBuilder.Entity("Mission4TreyJackson.Models.movieEntry", b =>
                {
                    b.HasOne("Mission4TreyJackson.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
